### ISSUE TITLE
[REQUEST] hub.docker.com?

### ISSUE THREAD

**Issue by shahram7** [Crissium/SilverDict#20]
Hi,
is it possible to put your app as docker file on [hub.docker.com](https://hub.docker.com/)? 
Best Regards, Shahram

**Comment by shahram7** [comment]
thank you very much @Crissium, sorry i had to search first.
I couldn't find any link to hub.docker on your github repo :(
But I've just deployed it and it works like a charm and now is scanning my sources

```
services:
  silverdict:
    image: mathdodger/silverdict:latest
    environment:
      ENABLE_FULL_TEXT_SEARCH: 'true'
      ENABLE_MORPHOLOGY_ANALYSIS: 'true'
    volumes:
      - /mnt/nvme/other/glossaries/silverdict:/root/.silverdict/source
      - cache:/root/.cache/SilverDict/
    restart: unless-stopped
    ports:
      - 2628:2628
volumes:
  cache:
```

Thank you for your time and effort : )
